# Generated by Django 5.1.1 on 2024-11-03 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_alter_customgpt_slug_gptresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='gpt',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='chat.customgpt'),
        ),
    ]
